#ifndef PERIPHERALS_H
#define PERIPHERALS_H

// GPIO
enum {
	PERIPHERAL_BASE = 0xFE000000,
	GPFSEL0         = PERIPHERAL_BASE + 0x200000,
	GPSET0          = PERIPHERAL_BASE + 0x20001C,
	GPCLR0          = PERIPHERAL_BASE + 0x200028,
	GPPUPPDN0       = PERIPHERAL_BASE + 0x2000E4
};

enum {
	GPIO_MAX_PIN       = 53,
	GPIO_FUNCTION_ALT5 = 2,
};

enum {
	Pull_None = 0,
};

// UART
enum {
	AUX_BASE        = PERIPHERAL_BASE + 0x215000,
	AUX_ENABLES     = AUX_BASE + 4,
	AUX_MU_IO_REG   = AUX_BASE + 64,
	AUX_MU_IER_REG  = AUX_BASE + 68,
	AUX_MU_IIR_REG  = AUX_BASE + 72,
	AUX_MU_LCR_REG  = AUX_BASE + 76,
	AUX_MU_MCR_REG  = AUX_BASE + 80,
	AUX_MU_LSR_REG  = AUX_BASE + 84,
	AUX_MU_CNTL_REG = AUX_BASE + 96,
	AUX_MU_BAUD_REG = AUX_BASE + 104,
	AUX_UART_CLOCK  = 500000000,
	UART_MAX_QUEUE  = 16 * 1024
};

// SYSTEM TIMER
enum {
	SYS_TIMER_BASE  = PERIPHERAL_BASE + 0x3000,
	SYS_TIMER_CS    = SYS_TIMER_BASE  + 0x00,
	SYS_TIMER_CLO   = SYS_TIMER_BASE  + 0x04,
	SYS_TIMER_CHI   = SYS_TIMER_BASE  + 0x08,
	SYS_TIMER_C0    = SYS_TIMER_BASE  + 0x0c,
	SYS_TIMER_C1    = SYS_TIMER_BASE  + 0x10,
	SYS_TIMER_C2    = SYS_TIMER_BASE  + 0x14,
	SYS_TIMER_C3    = SYS_TIMER_BASE  + 0x18,
};

#endif
